GET http://localhost:4000/user/checkjwt HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT3NjYXIiLCJlbWFpbCI6Im9zY2FyaW5vbm9nbWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY5MzEyMjc1MiwiZXhwIjoxNjkzMjA5MTUyfQ.gqtQPliZpX_cffKqONTFmfg946uzMKS4WxcWFGoGqYGX1LpUmGnVuiS84mKxTN3dRbYwsWT2CC3VXBRn13t-B0eatKIjsfH6-EMqKzQZsa81QFymbSRMKVyOGTXoxQWOhqKvhAZNJxJDJHU7I79UjEeB_uXD4fI-hL_H2JcS09frgUrh4kCOaO2Qzjpdu_bhPOY5Cge9X5br1XskhtpTYuFwJVM9y_jTwZ8xDwtvmcmgsaB95wRiplafqJykd4WdCZ_5hsnaR8Rc21o2USpMVUhQyXXDQZNxZ39-RsUL5WpPfj7c5CWgWe-FovKfloyPC7xyUCfvZxMYzu1yWoO5LA