GET http://localhost:4000/user/checkjwt HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJPc2NhciIsImVtYWlsIjoib3NjYXJpbm9ub2dtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwiaWF0IjoxNjk0NzIzODA4LCJleHAiOjE2OTQ4MTAyMDh9.Sa1gq8qDI1MJxV7o8wacajmYR8JmRgbuWkOXD3XiZxrrqx-zWdwHsGp_GYjfZvIjtfN0F7mvYlR-rXMNSZ1d_kDuLywtM2AiCk-jbQ-MG1Ukwb9Km52NZ-scLh-K5pm4sR88ywS1Tjp9X2JmcytL_rQOpt-iqR2tjjjn5eNTqz0_723yke9sNAGrvjRyz52V7hlx7c8k2Q890xLKbyYTIDsysEr6C87LRy8isE3kwWJ2iWFuNqzSJ6CS5Ma_ukF6etbbyw9aPsDGT7BEUB73zJLrUmlP5eq0LkluNv8SRjYanaaum2hZbwZQWLeNX_Xoi_1qy2JIldU4m8n41xtbYw