version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=login_system
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin2335
    ports:
      - 4001:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root2335
    ports:
      - 4002:80